model = "o3"
model_reasoning_effort = "medium"
sandbox_mode = 'danger-full-access'

[mcp_servers]
[mcp_servers.linear-mcp]
args = ['-y', 'mcp-remote', 'https://mcp.linear.app/mcp']
command = 'npx'
type = 'stdio'

[mcp_servers.notion]
args = ['-y', 'mcp-remote', 'https://mcp.notion.com/mcp']
command = 'npx'
type = 'stdio'
